[package]
name = "vault-node"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum = "0.8.9"
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
anyhow = "1"
config = { path = "../config" }
cggmp21 = { version = "0.6.3", features = ["curve-secp256k1"] }
rand_core = { version = "0.6", features = ["getrandom"] }
serde = { version = "1.0.229", features = ["derive"] }

[dev-dependencies]
round-based = { version = "0.4", features = ["sim"] }
